# Uncomment if commitlint is used
default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
    - id: check-json
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-private-key
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.10.0
  hooks:
    # Checks if your commit messages meet the conventional commit format
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-bn', '-w']
    - id: shellcheck

# For checking pre-commit configuration itself
- repo: meta
  hooks:
    # ensures that the configured hooks apply to at least one file in the repository
    - id: check-hooks-apply
    # ensures that `exclude` directives apply to any file in the repository
    - id: check-useless-excludes
